export const STATE_ACTIONS = Object.freeze({
    SET_STATUS: "SET_STATUS",
    SET_TWEETS_STATUS: "SET_TWEETS_STATUS",
    SET_USERS_STATUS: "SET_USERS_STATUS",
    SET_USERS_DETAILS_STATUS: "SET_USERS_DETAILS_STATUS"
});
